version: "2"
services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_HOST=%
    expose:
    # Opens port 3306 on the container
      - '3306'
    # Where our data will be persisted
    volumes:
      - 'my-db:/var/lib/mysql'
    container_name: mysql
  # webpacker:
  #   build: .
  #   env_file:
  #     - '.env.docker'
  #   command: ./bin/webpack-dev-server
  #   volumes:
  #     - .:/webpacker-example-app
  #   ports:
  #     - '3035:3035'
  app:
    build: .
    # command: bin/rails server --port 3000 --binding 0.0.0.0
    ports:
      - "3001:3000"
    environment:
      DB_USERNAME: root
      DB_PASSWORD: 
      DB_DATABASE: challenge_development
      DB_PORT: 3306
      DB_HOST: db
      RAILS_ENV: development
      RAILS_MAX_THREADS: 5

    volumes:
        - web-app:/challenge
        # - "./config/docker/database.yml:/challenge/config/database.yml"
    container_name: app
    links:
      - db:mysql
    depends_on:
      - db
    command:
      - ./config/docker/startup.sh

volumes:
  db:
  my-db: {}
  web-app: {}